### ISSUE TITLE
Resource specific variable tags

### ISSUE THREAD

**Issue by rb-nr** [banyansecurity/terraform-aws-banyan-accesstier#9]
Proposal

* `var.security_group_tags`
* `var.autoscaling_group_tags`
* `var.lb_tags`
* `var.target_group_tags`

Examples that use this system

* [hashicorp supported module for vpcs](https://github.com/terraform-aws-modules/terraform-aws-vpc) has `var.tags` but also has `var.vpc_tags`, `var.intra_subnet_tags`, `var.customer_gateway_tags`, etc.
* [hashicorp supported module for atlantis](https://github.com/terraform-aws-modules/terraform-aws-atlantis) has `var.tags` but also has `var.atlantis_security_group_tags`, `var.alb_http_security_group_tags`, `var.alb_https_security_group_tags`, etc.

**Comment by tradel** [comment]
What is the use case for this? When would you want different tags for each resource type in a module?
